security:
  jwt:
    secret: "demo-jwt"
    expiration: 86400000 # 1 dia em milisegundos
  public:
    path: "/public/**"

server:
  port: 8090
  servlet:
    context-path: /demo

spring:
  profiles:
    active: activatedProperties
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/simplesLogin?useTimezone=true&serverTimezone=America/Belem&createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    properties.hibernate.format_sql: true
  liquibase:
    change-log: classpath:/liquibase/liquibase-changelog.yml
    contexts: ${spring.profiles.active}